CREATE DATABASE TruYumDB;
USE TruYumDB;

CREATE TABLE MenuItems
(MenuItemId INT PRIMARY KEY NOT NULL,
[Name] VARCHAR(50),
Price SMALLMONEY,
Active VARCHAR(10),
DateOfLaunch DATETIME,
Category VARCHAR(20),
FreeDelivery VARCHAR(10)
);

CREATE TABLE Users
(UserId INT PRIMARY KEY NOT NULL,
UserName VARCHAR(50)
);

CREATE TABLE Cart
(CartItemId INT PRIMARY KEY NOT NULL,
MenuItemId INT NOT NULL,
UserId INT NOT NULL,
[Name] VARCHAR(50),
FreeDelivery VARCHAR(10),
Price SMALLMONEY,
CONSTRAINT UserFK FOREIGN KEY (UserId) REFERENCES Users(UserId),
CONSTRAINT ItemFK FOREIGN KEY (MenuItemId) REFERENCES MenuItems(MenuItemId)
);

--DROP TABLE MenuItems;
DROP TABLE Cart;